[Settings]
dark_mode = true
dark_mode_bg = "#282a36"
dark_mode_text = "#f8f8f2"
light_mode_bg = "#f8f8f2"
light_mode_text = "#282a36"
hotkey = "shift + left shift"
font_family = "Segoe UI"
font_size = 10
opacity = 1
borderless = true
rounded_corners = true
always_on_top = true
program_title = "kaboom"
no_results_text = "womp womp, no results found!"
verbatim_search = false
