[Settings]
dark_mode = true
colour_overlay_mode = false
dark_mode_bg = "#27282a"
dark_mode_text = "#FFFFFF"
light_mode_bg = "#FFFFFF"
light_mode_text = "#000000"
colour_overlay_bg = "#b5f4bb"
colour_overlay_text = "#000000"
qt_style = "Combinear.qss"
hotkey = "shift + left shift"
font_family = "Segoe UI"
font_size = 10
opacity = 1.0
translucent_background = false
borderless = true
rounded_corners = true
always_on_top = true
draggable_window = true
width = 600
height = 250
sidebar_mode = false
program_title = "kaboom"
no_results_text = "womp womp, no results found!"
verbatim_search = false
steam_path = "C:\\Program Files (x86)\\Steam"
bsman_path = "C:\\Users\\<CURRENT_USER>\\BSManager\\BSInstances"
search_start_menu = true
search_calculator = true
search_steam = true
search_bsman = true
