[light]
dark = false
background = "#F9F9F9"
foreground = "#383A42"
foreground2 = "#A0A1A7"
text = "#383A42"
icons = "#383A42"

[dark]
dark = true
background = "#1E2127"
foreground = "#ABB2BF"
foreground2 = "#383A42"
text = "#ABB2BF"
icons = "#ABB2BF"