[light]
dark = false
background = "#f2f2f2"
foreground = "#000000"
text = "#000000"
icons = "#000000"
button_qss = ""

[dark]
dark = true
background = "#27282a"
foreground = "#ffffff"
text = "#ffffff"
icons = "#ffffff"
button_qss = ""