[light]
dark = false
background = "#ffffff"
foreground = "#7289da"
text = "#000000"
icons = "#000000"

[dark]
dark = true
background = "#2c2f33"
foreground = "#7289da"
text = "#ffffff"
icons = "#ffffff"