[light]
dark = false
background = "#ffffff"
foreground = "#7289da"
foreground2 = "#7289da"
foreground3 = "#3a59c7"
text = "#000000"
icons = "#000000"
button_qss = "border: none; text-align: left;"

[dark]
dark = true
background = "#2c2f33"
foreground = "#7289da"
foreground2 = "#7289da"
foreground3 = "#3a59c7"
text = "#ffffff"
icons = "#ffffff"
button_qss = "border: none; text-align: left;"