[light]
dark = false
background = "#F8F8F2"
foreground = "#FF79C6"
foreground2 = "#FF79C6"
foreground3 = "#fc49b0"
text = "#282A36"
icons = "#FF79C6"
border = "none"
text-align = "left"

[dark]
dark = true
background = "#282A36"
foreground = "#FF79C6"
foreground2 = "#FF79C6"
foreground3 = "#fc49b0"
text = "#F8F8F2"
icons = "#FF79C6"
border = "none"
text-align = "left"