[light]
dark = false
background = "white"
foreground = "black"
text = "black"
icons = "black"
button_qss = "border: none; text-align: left;"

[dark]
dark = true
background = "black"
foreground = "white"
text = "white"
icons = "white"
button_qss = "border: none; text-align: left;"
