[light]
dark = false
background = "#f2f2f2"
foreground = "#000000"
foreground2 = "grey"
text = "#000000"
icons = "#000000"
button_qss = "border: none; text-align: left;"

[dark]
dark = true
background = "#27282a"
foreground = "#ffffff"
foreground2 = "grey"
text = "#ffffff"
icons = "#ffffff"
button_qss = "border: none; text-align: left;"