[light]
dark = false
background = "#fdf6e3"
foreground = "#859900"
text = "#073642"
icons = "#073642"
button_qss = "border: none; text-align: left;"

[dark]
dark = true
background = "#002b36"
foreground = "#859900"
text = "#93a1a1"
icons = "#839496"
button_qss = "border: none; text-align: left;"