[Settings]
theme = "kaboom"
theme_style = "dark"
qt_style = "Fusion.qss"
hotkey = "alt + space"
bgm = false
bgm_file = "griddy.wav"
bgm_volume = 0.0
auto_pause_bgm = true
font_family = "Segoe UI"
font_size = 12
opacity = 1.0
translucent_background = false
borderless = true
arrow_key_navigation = true
rounded_corners = true
always_on_top = true
draggable_window = true
hide_from_taskbar = true
window_animation = "Fade"
window_animation_speed = 0.005
width = 600
height = 250
open_on_startup = false
open_in_background = false
search_bar_location = "top"
sidebar_mode = false
program_icons = false
verbatim_search = false
max_results = 6
steam_path = "/Users/<CURRENT_USER>/Library/Application Support/Steam"
bsman_path = ""
search_start_menu = true
search_calculator = true
search_unit_conversion = true
search_filesystem = true
search_web = true
search_steam = true
search_bsman = true
default_search_engine = "google"

[Search_Engines]
google = "https://www.google.com/search?q="
duckduckgo = "https://duckduckgo.com/?q="
brave = "https://search.brave.com/search?q="
qwant = "https://www.qwant.com/?q="
ecosia = "https://www.ecosia.org/search?q="
startpage = "https://www.startpage.com/do/dsearch?query="
wikipedia = "https://en.wikipedia.org/wiki/Special:Search?search="
youtube = "https://www.youtube.com/results?search_query="
github = "https://github.com/search?q="
bing = "https://www.bing.com/search?q="
yahoo = "https://search.yahoo.com/search?p="
yandex = "https://yandex.com/search/?text="
baidu = "https://www.baidu.com/s?wd="
askcom = "https://www.ask.com/web?q="
aol = "https://search.aol.com/aol/search?q="